name: Training modello ML
on:
    push:
jobs:
    training:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                sparse-checkout: |
                    austria

            - uses: actions/setup-python@v5
              with:
                python-version: '3.12.7'
            - run: |
                python -m pip install --upgrade pip
              working-directory: austria
            - run: |
                pip install -r requirements.txt
              working-directory: austria
            - run: |
                python prova.py
              working-directory: austria
            - run: ls -la austria/

            - uses: actions/upload-artifact@v4
              with:
                name: modello-ml
                path: austria/modello_regressione.joblib